config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do

    devise_for :users

    root to: 'pages#index'

    get '/about', to: 'pages#about'
    get '/personal', to: 'pages#personal'
    post '/create_personal', to: 'pages#create_personal'
    get '/car', to: 'pages#car'
    get '/home', to: 'pages#home'

    resources :user_profiles
    resources :addresses
    resources :borrower_profiles
    resources :employments
    resources :personal_loans

  end
end

app/models/employment.rb
class Employment < ApplicationRecord
  belongs_to :user

  enum status: %i[full_time_employee part_time_employee self_employed seasonal_employee unemployed]

  def self.statuses_for_select
    statuses.map { |status, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.statuses.#{status}"),
       Employment.statuses[status]]
    }.to_h
  end

  def selected_status
    Employment.statuses[status]
  end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :set_employment, only: [:show, :edit, :update, :destroy]

  # GET /employments
  # GET /employments.json
  def index
    @employments = Employment.all
  end

  # GET /employments/1
  # GET /employments/1.json
  def show
  end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments
  # POST /employments.json
  def create
    @employment = Employment.new(employment_params)

    respond_to do |format|
      if @employment.save
        format.html { redirect_to @employment, notice: 'Employment was successfully created.' }
        format.json { render :show, status: :created, location: @employment }
      else
        format.html { render :new }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employments/1
  # PATCH/PUT /employments/1.json
  def update
    respond_to do |format|
      if @employment.update(employment_params)
        format.html { redirect_to @employment, notice: 'Employment was successfully updated.' }
        format.json { render :show, status: :ok, location: @employment }
      else
        format.html { render :edit }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1
  # DELETE /employments/1.json
  def destroy
    @employment.destroy
    respond_to do |format|
      format.html { redirect_to employments_url, notice: 'Employment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employment_params
      params.require(:employment).permit(:user_id, :status, :since, :employer, :title, :revenues)
    end
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employments/_form.html.erb
<%= form_with(model: employment, local: true) do |form| %>
  <% if employment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employment.errors.count, "error") %> prohibited this employment from being saved:</h2>

      <ul>
      <% employment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :since %>
    <%= form.datetime_select :since %>
  </div>

  <div class="field">
    <%= form.label :employer %>
    <%= form.text_field :employer %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :revenues %>
    <%= form.text_field :revenues %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employments/edit.html.erb
<h1>Editing Employment</h1>

<%= render 'form', employment: @employment %>

<%= link_to 'Show', @employment %> |
<%= link_to 'Back', employments_path %>

app/views/employments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th>Since</th>
      <th>Employer</th>
      <th>Title</th>
      <th>Revenues</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employments.each do |employment| %>
      <tr>
        <td><%= employment.user %></td>
        <td><%= employment.status %></td>
        <td><%= employment.since %></td>
        <td><%= employment.employer %></td>
        <td><%= employment.title %></td>
        <td><%= employment.revenues %></td>
        <td><%= link_to 'Show', employment %></td>
        <td><%= link_to 'Edit', edit_employment_path(employment) %></td>
        <td><%= link_to 'Destroy', employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employment', new_employment_path %>

app/views/employments/new.html.erb
<h1>New Employment</h1>

<%= render 'form', employment: @employment %>

<%= link_to 'Back', employments_path %>

app/views/employments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @employment.user %>
</p>

<p>
  <strong>Status:</strong>
  <%= @employment.status %>
</p>

<p>
  <strong>Since:</strong>
  <%= @employment.since %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @employment.employer %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employment.title %>
</p>

<p>
  <strong>Revenues:</strong>
  <%= @employment.revenues %>
</p>

<%= link_to 'Edit', edit_employment_path(@employment) %> |
<%= link_to 'Back', employments_path %>