config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do

    devise_for :users

    root to: 'pages#index'

    get '/about', to: 'pages#about'
    get '/personal', to: 'pages#personal'
    post '/create_personal', to: 'pages#create_personal'
    get '/car', to: 'pages#car'
    get '/home', to: 'pages#home'

    resources :user_profiles
    resources :addresses
    resources :borrower_profiles
    resources :employments
    resources :personal_loans

  end
end

app/models/personal_loan.rb
class PersonalLoan < ApplicationRecord
  belongs_to :user

  enum purpose: %i[vacation debt_consolidation credit_card_refinancing medical_expenses wedding moving_expenses other]

  def self.purposes_for_select
    purposes.map { |purpose, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.purposes.#{purpose}"),
       PersonalLoan.purposes[purpose]]
    }.to_h
  end

  def selected_purpose
    PersonalLoan.purposes[purpose]
  end
end

app/controllers/personal_loans_controller.rb
class PersonalLoansController < ApplicationController
  before_action :set_personal_loan, only: [:show, :edit, :update, :destroy]

  # GET /personal_loans
  # GET /personal_loans.json
  def index
    @personal_loans = PersonalLoan.all
  end

  # GET /personal_loans/1
  # GET /personal_loans/1.json
  def show
  end

  # GET /personal_loans/new
  def new
    @personal_loan = PersonalLoan.new
  end

  # GET /personal_loans/1/edit
  def edit
  end

  # POST /personal_loans
  # POST /personal_loans.json
  def create
    @personal_loan = PersonalLoan.new(personal_loan_params)

    respond_to do |format|
      if @personal_loan.save
        format.html { redirect_to @personal_loan, notice: 'Personal loan was successfully created.' }
        format.json { render :show, status: :created, location: @personal_loan }
      else
        format.html { render :new }
        format.json { render json: @personal_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_loans/1
  # PATCH/PUT /personal_loans/1.json
  def update
    respond_to do |format|
      if @personal_loan.update(personal_loan_params)
        format.html { redirect_to @personal_loan, notice: 'Personal loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_loan }
      else
        format.html { render :edit }
        format.json { render json: @personal_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_loans/1
  # DELETE /personal_loans/1.json
  def destroy
    @personal_loan.destroy
    respond_to do |format|
      format.html { redirect_to personal_loans_url, notice: 'Personal loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_loan
      @personal_loan = PersonalLoan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_loan_params
      params.require(:personal_loan).permit(:purpose, :amount, :user_id)
    end
end

app/helpers/personal_loans_helper.rb
module PersonalLoansHelper
end

app/views/personal_loans/_form.html.erb
<%= form_with(model: personal_loan, local: true) do |form| %>
  <% if personal_loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personal_loan.errors.count, "error") %> prohibited this personal_loan from being saved:</h2>

      <ul>
      <% personal_loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :purpose %>
    <%= form.text_field :purpose %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personal_loans/edit.html.erb
<h1>Editing Personal Loan</h1>

<%= render 'form', personal_loan: @personal_loan %>

<%= link_to 'Show', @personal_loan %> |
<%= link_to 'Back', personal_loans_path %>

app/views/personal_loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal Loans</h1>

<table>
  <thead>
    <tr>
      <th>Purpose</th>
      <th>Amount</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_loans.each do |personal_loan| %>
      <tr>
        <td><%= personal_loan.purpose %></td>
        <td><%= personal_loan.amount %></td>
        <td><%= personal_loan.user %></td>
        <td><%= link_to 'Show', personal_loan %></td>
        <td><%= link_to 'Edit', edit_personal_loan_path(personal_loan) %></td>
        <td><%= link_to 'Destroy', personal_loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal Loan', new_personal_loan_path %>

app/views/personal_loans/new.html.erb
<h1>New Personal Loan</h1>

<%= render 'form', personal_loan: @personal_loan %>

<%= link_to 'Back', personal_loans_path %>

app/views/personal_loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Purpose:</strong>
  <%= @personal_loan.purpose %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @personal_loan.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @personal_loan.user %>
</p>

<%= link_to 'Edit', edit_personal_loan_path(@personal_loan) %> |
<%= link_to 'Back', personal_loans_path %>