config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do

    devise_for :users

    root to: 'pages#index'

    get '/about', to: 'pages#about'
    get '/personal', to: 'pages#personal'
    post '/create_personal', to: 'pages#create_personal'
    get '/car', to: 'pages#car'
    get '/home', to: 'pages#home'

    resources :user_profiles
    resources :addresses
    resources :borrower_profiles
    resources :employments
    resources :personal_loans

  end
end

app/models/borrower_profile.rb
class BorrowerProfile < ApplicationRecord
  belongs_to :user

  enum ownership: %i[owner tenant]
  enum credit_appreciation: %i[poor fair good very_good excellent]

  def self.ownerships_for_select
    ownerships.map { |ownership, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.ownerships.#{ownership}"),
       BorrowerProfile.ownerships[ownership]]
    }.to_h
  end

  def selected_ownership
    BorrowerProfile.ownerships[ownership]
  end

  def self.credit_appreciations_for_select
    credit_appreciations.map { |credit_appreciation, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.credit_appreciations.#{credit_appreciation}"),
       BorrowerProfile.credit_appreciations[credit_appreciation]]
    }.to_h
  end

  def selected_credit_appreciation
    BorrowerProfile.credit_appreciations[credit_appreciation]
  end
end

app/controllers/borrower_profiles_controller.rb
class BorrowerProfilesController < ApplicationController
  before_action :set_borrower_profile, only: [:show, :edit, :update, :destroy]

  # GET /borrower_profiles
  # GET /borrower_profiles.json
  def index
    @borrower_profiles = BorrowerProfile.all
  end

  # GET /borrower_profiles/1
  # GET /borrower_profiles/1.json
  def show
  end

  # GET /borrower_profiles/new
  def new
    @borrower_profile = BorrowerProfile.new
  end

  # GET /borrower_profiles/1/edit
  def edit
  end

  # POST /borrower_profiles
  # POST /borrower_profiles.json
  def create
    @borrower_profile = BorrowerProfile.new(borrower_profile_params)

    respond_to do |format|
      if @borrower_profile.save
        format.html { redirect_to @borrower_profile, notice: 'Borrower profile was successfully created.' }
        format.json { render :show, status: :created, location: @borrower_profile }
      else
        format.html { render :new }
        format.json { render json: @borrower_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrower_profiles/1
  # PATCH/PUT /borrower_profiles/1.json
  def update
    respond_to do |format|
      if @borrower_profile.update(borrower_profile_params)
        format.html { redirect_to @borrower_profile, notice: 'Borrower profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrower_profile }
      else
        format.html { render :edit }
        format.json { render json: @borrower_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrower_profiles/1
  # DELETE /borrower_profiles/1.json
  def destroy
    @borrower_profile.destroy
    respond_to do |format|
      format.html { redirect_to borrower_profiles_url, notice: 'Borrower profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrower_profile
      @borrower_profile = BorrowerProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrower_profile_params
      params.require(:borrower_profile).permit(:user_id, :bankcruptcy, :ownership, :other_revenues, :assets, :credit_appreciation)
    end
end

app/helpers/borrower_profiles_helper.rb
module BorrowerProfilesHelper
end

app/views/borrower_profiles/_form.html.erb
<%= form_with(model: borrower_profile, local: true) do |form| %>
  <% if borrower_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borrower_profile.errors.count, "error") %> prohibited this borrower_profile from being saved:</h2>

      <ul>
      <% borrower_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :bankcruptcy %>
    <%= form.check_box :bankcruptcy %>
  </div>

  <div class="field">
    <%= form.label :ownership %>
    <%= form.number_field :ownership %>
  </div>

  <div class="field">
    <%= form.label :other_revenues %>
    <%= form.text_field :other_revenues %>
  </div>

  <div class="field">
    <%= form.label :assets %>
    <%= form.text_field :assets %>
  </div>

  <div class="field">
    <%= form.label :credit_appreciation %>
    <%= form.number_field :credit_appreciation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/borrower_profiles/edit.html.erb
<h1>Editing Borrower Profile</h1>

<%= render 'form', borrower_profile: @borrower_profile %>

<%= link_to 'Show', @borrower_profile %> |
<%= link_to 'Back', borrower_profiles_path %>

app/views/borrower_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Borrower Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bankcruptcy</th>
      <th>Ownership</th>
      <th>Other revenues</th>
      <th>Assets</th>
      <th>Credit appreciation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrower_profiles.each do |borrower_profile| %>
      <tr>
        <td><%= borrower_profile.user %></td>
        <td><%= borrower_profile.bankcruptcy %></td>
        <td><%= borrower_profile.ownership %></td>
        <td><%= borrower_profile.other_revenues %></td>
        <td><%= borrower_profile.assets %></td>
        <td><%= borrower_profile.credit_appreciation %></td>
        <td><%= link_to 'Show', borrower_profile %></td>
        <td><%= link_to 'Edit', edit_borrower_profile_path(borrower_profile) %></td>
        <td><%= link_to 'Destroy', borrower_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Borrower Profile', new_borrower_profile_path %>

app/views/borrower_profiles/new.html.erb
<h1>New Borrower Profile</h1>

<%= render 'form', borrower_profile: @borrower_profile %>

<%= link_to 'Back', borrower_profiles_path %>

app/views/borrower_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @borrower_profile.user %>
</p>

<p>
  <strong>Bankcruptcy:</strong>
  <%= @borrower_profile.bankcruptcy %>
</p>

<p>
  <strong>Ownership:</strong>
  <%= @borrower_profile.ownership %>
</p>

<p>
  <strong>Other revenues:</strong>
  <%= @borrower_profile.other_revenues %>
</p>

<p>
  <strong>Assets:</strong>
  <%= @borrower_profile.assets %>
</p>

<p>
  <strong>Credit appreciation:</strong>
  <%= @borrower_profile.credit_appreciation %>
</p>

<%= link_to 'Edit', edit_borrower_profile_path(@borrower_profile) %> |
<%= link_to 'Back', borrower_profiles_path %>