config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do

    devise_for :users

    root to: 'pages#index'

    get '/about', to: 'pages#about'
    get '/personal', to: 'pages#personal'
    post '/create_personal', to: 'pages#create_personal'
    get '/car', to: 'pages#car'
    get '/home', to: 'pages#home'

    resources :user_profiles
    resources :addresses
    resources :borrower_profiles
    resources :employments
    resources :personal_loans

  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one :address, as: 'addressable'


end

app/controllers/user_profiles_controller.rb
# UserProfiles controller
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: %i[show edit update destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: I18n.t("controllers.#{action_name}.success", model: controller_model_name) }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: I18n.t("controllers.#{action_name}.success", model: controller_model_name) }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: I18n.t("controllers.#{action_name}.success", model: controller_model_name) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_profile
    @user_profile = UserProfile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_profile_params
    params.require(:user_profile).permit(:user_id, :firstname, :lastname, :birthdate, :phone, :SIN, :address_id)
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_with(model: user_profile, local: true) do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.datetime_select :birthdate %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :sin %>
    <%= form.text_field :sin %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.text_field :address_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<%- model_class = UserProfile -%>
<h1><%= model_class.model_name.human %>: <%= t('helpers.links.edit') %></h1>

<%= render 'user_profiles/form', user_profile: @user_profile %>

app/views/user_profiles/index.html.erb
<%- model_class = UserProfile -%>
<h1><%= model_class.model_name.human(count: 2) %></h1>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= User.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:birthdate) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:sin) %></th>
      <th><%= Address.model_name.human %></th>
      <th class="text-right">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.firstname %></td>
        <td><%= user_profile.lastname %></td>
        <td><%= user_profile.user.email %></td>
        <td><%= user_profile.birthdate %></td>
        <td><%= user_profile.phone %></td>
        <td>*** *** <%= user_profile.sin %></td>
        <td><%= render 'addresses/address_inline', address: user_profile.address if user_profile.address.present? %></td>
        <td class="text-right">
          <%= link_to t('helpers.links.show'), user_profile, class: 'btn btn-sm btn-light' %>
          <%= link_to t('helpers.links.edit'), edit_user_profile_path(user_profile), class: 'btn btn-sm btn-light' %>
          <%= link_to t('helpers.links.destroy'), user_profile, method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= t('.no_user_profiles_yet') if @user_profiles.empty? %></p>

<br>

<%= link_to t('helpers.links.new'), new_user_profile_path, class: 'btn btn-primary' %>

app/views/user_profiles/new.html.erb
<%- model_class = UserProfile -%>
<h1><%= model_class.model_name.human %>: <%= t('helpers.links.new') %></h1>

<%= render 'user_profiles/form', user_profile: @user_profile %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_profile.user %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user_profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user_profile.lastname %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user_profile.birthdate %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user_profile.phone %>
</p>

<p>
  <strong>Sin:</strong>
  <%= @user_profile.SIN %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user_profile.address %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>